config/routes.rb
Rails.application.routes.draw do
  get 'displays/index'
  post 'calendars/generate_carwash'
  
  resources :calendars
  resources :users
  resources :displays

  root 'calendars#index'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
	belongs_to :user
end

app/models/display.rb
class Display < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :calendars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all  
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show  

  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  def generate_carwash

    collaborators = User.order('name').map(&:id)
    carwash_available_spots = 5
    current_date = Date.today

    last_spot = Calendar.last

    if last_spot != nil
      current_date = last_spot.date
      count = Calendar.where(date:current_date).count
      missing_spots = carwash_available_spots - count
      puts "#{missing_spots.inspect}"
      #fill missing spots
      if missing_spots>1
        missing_spots.times do
         weekdays=current_date.weekday?
         if weekdays==false
          current_date += 2
        end
        collaborator = collaborators.shift
        
        if(collaborator!=nil)
          carwash = Calendar.new
          carwash.user_id = collaborator
          carwash.date = current_date
          carwash.save        
          puts "#{collaborator.inspect+" "+current_date.inspect}"
        end

      end
    end
    current_date += 1  
  end

  while(collaborators.count > 0) do

   weekdays=current_date.weekday?
   if weekdays==false
    current_date += 2
  end
  carwash_available_spots.times do
    
    collaborator = collaborators.shift

    if(collaborator!=nil)
      carwash = Calendar.new
      carwash.user_id = collaborator
      carwash.date = current_date
      carwash.save  
    end

  end
  current_date += 1       

end



redirect_to :controller => 'calendars', :action => 'index'
end




def create
  @calendar = Calendar.new(calendar_params)

  respond_to do |format|
    if @calendar.save
      format.html { redirect_to @calendar, notice: 'The Carwash schedule was successfully created.' }
      format.json { render :show, status: :created, location: @calendar }
    else
      format.html { render :new }
      format.json { render json: @calendar.errors, status: :unprocessable_entity }
    end
  end

end


def update
  respond_to do |format|
    if @calendar.update(calendar_params)
      format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
      format.json { render :show, status: :ok, location: @calendar }
    else
      format.html { render :edit }
      format.json { render json: @calendar.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
  @calendar.destroy
  respond_to do |format|
    format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:date, :user_id)
    end

  end

app/controllers/displays_controller.rb
class DisplaysController < ApplicationController
  def index
  	@date= Calendar.where(:all, :conditions => ["date between ? AND ?", DateTime.now.beginning_of_month, DateTime.now.end_of_month]) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/displays_helper.rb
module DisplaysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calendars</h1>
<%= button_to "Generate Carwash Role ", { :controller => "calendars", :action => "generate_carwash"} %>
<table cellspacing="10">
  <thead>
    <tr>
      <th>Date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
    <% if calendar.user_id != nil %>
      <tr>
        <td><%= calendar.date.strftime('%d'+" "+'%b'+" "+'%Y') %></td>
        <td><b><%= @counter %>(<%= calendar.user.id %>)</b> <%= calendar.user.name+" "+calendar.user.lastname  %></td>
        <!-- <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %>
        </td>
        <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<!-- 
<%= link_to 'New Calendar', new_calendar_path %>
 -->

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @calendar.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @calendar.user_id %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>

app/views/displays/index.html.erb
<h1>Displays</h1>
<p>Find me in app/views/displays/index.html.erb</p>

<table cellpadding="4">

<tr>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
</tr>

<tr>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
</tr>

<tr>
<td>15</td>
<td>16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td>21</td>
</tr>

<tr>
<td>22</td>
<td>23</td>
<td>24</td>
<td>25</td>
<td>26</td>
<td>27</td>
<td>28</td>
</tr>
<tr>
<td>29</td>
<td>30</td>
<td>31</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

</table>

<% @date.each do |d| %>
	<%= d.date %>
<% end %>

 u = User.all.map(&:id)
x = u.slice!(0...5)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carwash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>